### ISSUE TITLE
カジュアル面談させて頂きたくご連絡いたしました

### ISSUE THREAD

**Issue by yppon** [satoryu/satoryu.github.io#2]
## 企業名
[株式会社Traimmu](https://www.traimmu.com/)

## ご担当者様 氏名
共同創業者・CTO　佐野 貴之

## お問い合わせ内容
偶然Twitterで佐藤様のアカウントをお見かけし、#転職活動中のタグとプロフィールを拝見してご連絡を差し上げました。

弊社は「若者の価値を最大化する」というビジョンの下、長期インターンに特化した求人サイト「InfrA」と学生向けWebメディア「co-media」を開発・運営しておりまして、今春には「InfrA」を大幅なリニューアルに着手する予定です（システムは完全にリプレイスになるかもしれません）。

技術的には、主にLaravel, GraphQL, Vue.js, React.js, React Native等を使ってWebおよびiOSアプリを開発しておりますが、フルタイムのエンジニアが私1名しかおらず、フルタイムのエンジニアを数名（テックリード1名、エンジニア社員1~2名）募集しております。
cf.) https://www.wantedly.com/projects/273119

佐藤様のご経歴やご経験から、ぜひ一度弊社のテックリード候補としてカジュアル面談をさせて頂きたいと考えております。

もし少しでも弊社の事業や開発に興味がございましたら、30分〜1時間ほど面談のお時間を頂けないでしょうか？
お忙しいとは思いますがご検討どうぞよろしくお願いいたします。

**Comment by satoryu** [comment]
回答遅くなり申し訳ありません。
ご連絡ありがとうございます。

申し訳ありませんが、御社のようなスタートアップ企業は現在候補から外しており、お誘いいただきましても一律でお断りさせていただいております。

ご期待に応えられず申し訳ありませんが、ご理解ください。
